### ISSUE TITLE
分屏后有些情况下面包屑不显示

### ISSUE THREAD

**Issue by littlecoby** [OpaqueGlass/syplugin-fakeDocBreadcrumb#10]
版本：思源v2.10.13，面包屑v0.2.8
系统：windows11

问题：
分屏后有些情况下新分出来的页签里面包屑不显示。
根据下面的测试，看上去是同一个文档分屏后，新页签里没有显示面包屑。

同一个文档的情况：
菜单点击向右/下分屏：不显示
alt+点击文档树打开：不显示
向右分屏后把原页签关闭：新页签里重新显示

不同文档的情况：
鼠标拖动分屏：显示
菜单点击向右/下分屏并移动：显示
alt+点击文档树打开：显示，但有些延迟

**Comment by OpaqueGlass** [comment]
感谢反馈，暂时不在集市更新；如果可以，请下载[v0.2.9-beta1](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.9-beta1)测试。

**Comment by littlecoby** [comment]
> 感谢反馈，暂时不在集市更新；如果可以，请下载[v0.2.9-beta1](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.9-beta1)测试。

okok，我等集市版本好了

**Comment by littlecoby** [comment]
> 感谢反馈，暂时不在集市更新；如果可以，请下载[v0.2.9-beta1](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.9-beta1)测试。

v0.2.9
分屏后需要点一下页签才显示面包屑，不知道是不是设计如此呢

**Comment by OpaqueGlass** [comment]
emm，分屏后会对聚焦到的文档更新面包屑，从文档树分屏打开文档的话，我这里正常，有空的时候我再试试，能复现的话就修复

**Comment by littlecoby** [comment]
> emm，分屏后会对聚焦到的文档更新面包屑，从文档树分屏打开文档的话，我这里正常，有空的时候我再试试，能复现的话就修复
> 
> ![未复现说明](https://user-images.githubusercontent.com/52985952/285143249-d7084b8a-ea04-4c5b-a926-7f72a7634cad.gif) [ ![未复现说明](https://user-images.githubusercontent.com/52985952/285143249-d7084b8a-ea04-4c5b-a926-7f72a7634cad.gif) ](https://user-images.githubusercontent.com/52985952/285143249-d7084b8a-ea04-4c5b-a926-7f72a7634cad.gif) [ ](https://user-images.githubusercontent.com/52985952/285143249-d7084b8a-ea04-4c5b-a926-7f72a7634cad.gif)

噢 我测的是右键单击页签后的分屏

**Comment by OpaqueGlass** [comment]
页签打开的没有获得焦点，理论上不会显示；我有空再改改代码，但还没思路😂

**Comment by littlecoby** [comment]
> 噢，我测的是右键单击页签后的分屏
> 
> 额，好像有时挺灵的，有时又不大行，不大清楚怎么稳定复现

我本来想说的是，即使点击了页签，有时也弹不出面包屑，但还不清楚怎么稳定复现 emm

**Comment by OpaqueGlass** [comment]
emm，分屏出来的我这重现了，不太确定具体是哪里的bug，接下来会大改一下，尝试使用官方的接口；

**Comment by OpaqueGlass** [comment]
似乎是修好了，愿意花时间测试一下吗？ https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.10-beta1

**Comment by littlecoby** [comment]
> 似乎是修好了，愿意花时间测试一下吗？ https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.10-beta1 Release发错了 9:21的时候重新发布了一下。

okok，刚看到，我晚点测试一下

**Comment by littlecoby** [comment]
> 似乎是修好了，愿意花时间测试一下吗？ https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.10-beta1 Release发错了 9:21的时候重新发布了一下。

试了下，感觉流畅了好多，分屏到哪里都能瞬间显示面包屑，赞！

在Savor主题下面包屑显示有和图标重叠的bug，思源默认主题里显示是正常的，是向主题提issue还是这里提呢
![1701050153699](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/27865589/195d0517-defe-44d5-a526-bf4586dd826a)

**Comment by OpaqueGlass** [comment]
savor主题吗？我这里看着还挺正常的？重启一下试试？
![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/52985952/5421a80e-e14b-40bc-b970-ae46533ad037)

**Comment by OpaqueGlass** [comment]
哦，复现了，我看看，应该是我这的问题

**Comment by OpaqueGlass** [comment]
应该是修好了，一会儿发个版本，在集市上下载就好

**Comment by littlecoby** [comment]
> > 似乎是修好了，愿意花时间测试一下吗？ https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.10-beta1 Release发错了 9:21的时候重新发布了一下。
> 
> 试了下，感觉流畅了好多，分屏到哪里都能瞬间显示面包屑，赞！
> 
> 在Savor主题下面包屑显示有和图标重叠的bug，思源默认主题里显示是正常的，是向主题提issue还是这里提呢 ![1701050153699](https://private-user-images.githubusercontent.com/27865589/285703312-195d0517-defe-44d5-a526-bf4586dd826a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMTU1MjIsIm5iZiI6MTcwMjAxNTIyMiwicGF0aCI6Ii8yNzg2NTU4OS8yODU3MDMzMTItMTk1ZDA1MTctZGVmZS00NGQ1LWE1MjYtYmY0NTg2ZGQ4MjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDA2MDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MjU1ODk2ZWM5YjRlZDJmYTZlYjY2MmYyMzg0ODFhNGM3OWFjYjg1OGRhODE0NWE5NGVjNmMxOWFhZGZhNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K8Vre1EviWEWw4kp34aekl0q0ENkc0APPa1499eAsP4)

最近savor升级到v3.7.7之后，又出现这个图标重叠的问题了

**Comment by OpaqueGlass** [comment]
emm，还没复现，或许需要麻烦你截图一下插件的设置和重叠的情况；

> 但我发现别的问题了，点击面包屑的笔记本部分竟然会关闭标签页😅

**Comment by OpaqueGlass** [comment]
哦，复现了，上面的当我没说

**Comment by littlecoby** [comment]
> 哦，复现了，上面的当我没说。
> 
> 先加个自定义 css 凑合一下吧，暂时不想发新版；
> 

okok

**Comment by OpaqueGlass** [comment]
已在v0.2.11中发布相关更改，感谢反馈。
