### ISSUE TITLE
分屏后通过>打开的文档出现位置的问题

### ISSUE THREAD

**Issue by littlecoby** [OpaqueGlass/syplugin-fakeDocBreadcrumb#12]
右半屏中面包屑打开的文档出现在了左边
下半屏中面包屑打开的文档出现在了上边

**Comment by OpaqueGlass** [comment]
哦还有这个问题，这块我看看怎么改哈；现在是文档打开到当前拥有焦点的文档所在页签栏

**Comment by littlecoby** [comment]
> 哦还有这个问题，这块我看看怎么改哈；现在是文档打开到当前拥有焦点的文档所在页签栏

原来是打开到焦点在的栏，有道理的样子 emm

**Comment by OpaqueGlass** [comment]
😂能实现的话就做成设置项

**Comment by littlecoby** [comment]
> 😂能实现的话就做成设置项

哈哈哈，遇事不决，设置解决

**Comment by OpaqueGlass** [comment]
这个问题应该是修好了；目前还在测试中（我自己不太用分屏，所以可能测不出问题）；如果可以的话，麻烦下载仓库的zip压缩包测试一下，谢谢❤

**Comment by OpaqueGlass** [comment]
已在v0.2.11中发布相关更改，感谢反馈。

**Comment by littlecoby** [comment]
> 这个问题应该是修好了；目前还在测试中（我自己不太用分屏，所以可能测不出问题）；如果可以的话，麻烦下载仓库的zip压缩包测试一下，谢谢❤

才看到。。赞！
