### ISSUE TITLE
同时开启「允许悬停显示浮窗」和「与块面包屑在同一行显示」选项后，点击面包屑出现异常

### ISSUE THREAD

**Issue by TCOTC** [OpaqueGlass/syplugin-fakeDocBreadcrumb#17]
同时开启「允许悬停显示浮窗」和「与块面包屑在同一行显示」选项后，点击面包屑中的上级文档不会打开新页签，而是切换当前编辑器的内容为点击的文档的内容，并且标题还是上一个文档的标题

**Comment by OpaqueGlass** [comment]
感谢反馈，如果可以，请使用此版本测试一下：https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.13-beta1

**Comment by TCOTC** [comment]
这个 issue 的问题应该解决了

**Comment by OpaqueGlass** [comment]
隔壁的issue呢？我应该是一块修的
