### ISSUE TITLE
点击面包屑中的「笔记本」层级，会导致文档关闭

### ISSUE THREAD

**Issue by TCOTC** [OpaqueGlass/syplugin-fakeDocBreadcrumb#19]
在打开「与块面包屑在同一行显示」选项的情况下，面包屑可点击。

点击面包屑中的其他层级会正常打开文档；而点击最前面的「笔记本」层级，会导致当前文档关闭。

我认为在点击「笔记本」层级后不应该有任何操作。

**Comment by OpaqueGlass** [comment]
嗯嗯，感谢反馈，刚发现了😂

**Comment by TCOTC** [comment]
面包屑中的「笔记本」层级已经无法点击

https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.13-rc2
