### ISSUE TITLE
增加设置项

### ISSUE THREAD

**Issue by OpaqueGlass** [OpaqueGlass/syplugin-fakeDocBreadcrumb#2]
- [x] 文档层级大于x时，显示前y个和后z个；
- [x] 支持不显示笔记本层级；

**Comment by HowcanoeWang** [comment]
修改 https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/blob/f3e25962e595c984778a6836b71712a3bc1a6e1e/index.js#L143C15-L143C15
这边的height第二个选项“540px”，可以设置PC端的设置UI高度，改成“80vh”可以解决设置加载不完全的问题(占页面高度的80%的意思)

**Comment by OpaqueGlass** [comment]
感谢指正；

ps上下能滚动，当时抄的示例，也没想过要改😂

**Comment by HowcanoeWang** [comment]
主要是显示不全旁边也没有滚动条提示，然后还和底部完美契合，完全没意识到可以滚动，还是仔细看了说明才发现的😄️
