### ISSUE TITLE
子文档菜单显示文档图标

### ISSUE THREAD

**Issue by TCOTC** [OpaqueGlass/syplugin-fakeDocBreadcrumb#20]
就是这个地方，看起来像是给图标留的位置：

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/78434827/4b4028e8-5130-400e-a3e6-ea7a968f6bd5)

**Comment by OpaqueGlass** [comment]
感谢反馈，如果可以，麻烦下载测试：https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/releases/tag/v0.2.13-rc2

**Comment by TCOTC** [comment]
希望能像文档树那样显示默认图标：

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/78434827/5f3d1f1f-d042-444a-a467-f5ef5418eb5e)

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/78434827/ca9247db-03f3-46c9-9b44-ce6dabb05473)

**Comment by OpaqueGlass** [comment]
有设置的 
![Uploading image.png…]()

**Comment by TCOTC** [comment]
感谢开发，现在插件非常好用了

**Comment by OpaqueGlass** [comment]
感谢反馈和测试，issue先关了哈；

> emm上个版本忘记加标签了；版本号也没更新，要区分子文档图标的话需要等集市重新索引后（大概两三个小时吧）删除插件重新下载。
