### ISSUE TITLE
用蓝色字体标识当前路径

### ISSUE THREAD

**Issue by TCOTC** [OpaqueGlass/syplugin-fakeDocBreadcrumb#22]
我感觉这里应该可以用蓝色的字体：（加粗的区分度还是不高）

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/78434827/71827efb-14c3-4fe6-a245-6d25e1c5152c)

就像这个：

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/78434827/bfcaa9d8-f70e-451b-8581-99968cb84292)

**Comment by OpaqueGlass** [comment]
感谢反馈，这个部分我改为使用API，这样可以跟随主题；加粗同时保留。
