### ISSUE TITLE
限制错误提示输出&修复无页签时报错的问题

### ISSUE THREAD

**Issue by frostime** [OpaqueGlass/syplugin-fakeDocBreadcrumb#5]
![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/27268127/e1c3c0e6-cbd5-4e31-a704-1861d4ade60f)

满屏红黄看着很难受，可否在 build 版本中不要输出 exception

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/27268127/a7959512-4c27-4cd0-901e-a23bad9395b7)
![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/27268127/1283ddf4-f29f-4e32-b4fc-a0a7d5c30934)

**Comment by OpaqueGlass** [comment]
ok，下个版本加个判断，遇到window["debug"]为true再输出。

**Comment by OpaqueGlass** [comment]
我觉得正常不该遇到这个问题，重试一次一般就好了，你的思源版本是？我过会儿检查一下代码。

**Comment by frostime** [comment]
2.9.1-dev1

**Comment by OpaqueGlass** [comment]
ok，感谢反馈，下个版本修
