### ISSUE TITLE
开启插件后，会使大纲跳转不准

### ISSUE THREAD

**Issue by tcmtom** [OpaqueGlass/syplugin-fakeDocBreadcrumb#6]
开启插件之后，大纲跳转位置的顶部，会插件遮挡。

**Comment by OpaqueGlass** [comment]
感谢反馈。
这应该是和插入在块面包屑上方有关。目前没有太好的兼容方法，等我后续研究一下。

目前我的猜想是顶替原有块面包屑的位置，但可能有点问题，这个将在下周尝试。

**Comment by OpaqueGlass** [comment]
> 目前我的猜想是顶替原有块面包屑的位置，但可能有点问题，这个将在下周尝试。

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/52985952/ab32b3cd-0358-4fe0-9766-74a6e85d3c75)

除了有亿点奇怪以外，好像没啥问题，我再试用一下，没明显问题的话会作为可选项提供；

> 可以和D大一起探讨一下，看看能不能检测上面的高度

在siyuan仓库那边提issue了，V姐说会重新计算一下位置，请关注：https://github.com/siyuan-note/siyuan/issues/8674

**Comment by OpaqueGlass** [comment]
现在应该可以在集市下载v0.2.4版本了。如果还有问题，可以跟帖回复，或者新开issue，谢谢。
