### ISSUE TITLE
[疑似Bug] 插件和 alt +y 模式冲突

### ISSUE THREAD

**Issue by frostime** [OpaqueGlass/syplugin-fakeDocBreadcrumb#7]
## 触发条件

1. 使用本插件的情况
2. 使用 alt+y 模式

## 具体表现

此时思源的窗口将无法正常拖动。

-  alt +y 之前，窗口可以任意拖动

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/27268127/a4849907-1f66-42b5-8111-f6fdeafcb6fd)

- 开启 alt +y 并关闭插件，依然可以通过顶栏拖动窗口

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/27268127/087cf5a9-0405-4d58-aef5-68ca23c4f365)

- 开启 alt +y 并开启插件，窗口无法再任意拖动

![image](https://github.com/OpaqueGlass/syplugin-fakeDocBreadcrumb/assets/27268127/1d1b910b-bbab-44fd-8db5-85caddd335a4)

**Comment by OpaqueGlass** [comment]
感谢反馈，应该是修复了，等集市更新。

> 麻烦忽略之前的回复，之前想多了hhh😅

**Comment by OpaqueGlass** [comment]
已更新。如果还有其他问题，麻烦继续反馈，谢谢。❤️
